[package]
name = "db"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
bson = { version = "2.6.1", features = ["chrono-0_4"] }
futures = "0.3.28"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.19"
model = { path = "../../crates/model" }
mongodb = "2.6.0"
serde = "1.0.164"
serde_json = "1.0.99"
stop-words = "0.7.2"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
chrono = "0.4.26"
include_dir = "0.7.3"
pretty_assertions = "1.3.0"
regex = "1.9.5"
tempdir = "0.3.7"
