[package]
name = "model"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
bson = { version = "2.6.1", features = ["chrono-0_4"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
